### ISSUE TITLE
dusk on crates.io

### ISSUE THREAD

**Issue by zachwolfe** [aloucks/vki#14]
Hi aloucks,

Apologies in advance, as I know this is not an appropriate place to ask a question like this. I couldn't find any other contact info for you, or I would have used it.

You seem to be the owner of the "[dusk](https://crates.io/crates/dusk)" crate on crates.io, which has no content and hasn't been updated in two years. I have a programming language called Dusk that I recently started distributing on crates.io under the name "[dusklang](https://crates.io/crates/dusklang)". This is not ideal, since users who install Dusk using Cargo have to type "dusklang" to run the compiler on the command line instead of the desired "dusk." Admittedly, crates.io is highly unlikely to be the main distribution method for Dusk in the long term, but at least in the short term I would love to be able to use "dusk" if it were up for grabs. Would you be willing to transfer ownership of the crate to me?

Thanks, and sorry again for creating an issue on an unrelated project.

**Comment by aloucks** [comment]
> This is not ideal, since users who install Dusk using Cargo have to type "dusklang" to run the compiler on the command line instead of the desired "dusk."

You don't have to name the binary after the crate name. For example, [ripgrep](https://github.com/BurntSushi/ripgrep/blob/87b33c96c02b5d728324632956d301ef3d234f80/Cargo.toml#L21-L24) installs as a binary called `rg`.

I reserved the name for a project that I am working on. I'm not sure if or when it will be published on crates.io, but all of the other names that I had considered were already taken. 

Considering that your project is at the very early stages, and there is a work-around for your immediate issue (the binary name), and that you likely won't use crates.io as a long-term distribution method (which I don't believe it should be), I'm inclined to keep the project name reserved for if/when I'm ready to use it (at least for now).

**Comment by zachwolfe** [comment]
> You don't have to name the binary after the crate name. For example, [ripgrep](https://github.com/BurntSushi/ripgrep/blob/87b33c96c02b5d728324632956d301ef3d234f80/Cargo.toml#L21-L24) installs as a binary called `rg`.

Oops, I had no idea this was a thing. That does appear to solve my immediate issue. Thanks!
